-- Histórico do Atendente Virtual
-- As tabelas já foram provisionadas no projeto durante a implementação inicial.
-- Este arquivo mantém a mudança reproduzível e idempotente.

create table if not exists public.bot_conversations (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null unique,
  treatment_context text,
  treatment_name text,
  page_path text,
  city text,
  route text,
  intent text,
  status text not null default 'aberta' check (status in ('aberta','finalizada','whatsapp')),
  started_at timestamptz not null default now(),
  last_message_at timestamptz not null default now(),
  message_count integer not null default 0 check (message_count >= 0),
  whatsapp_handoff boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.bot_messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null references public.bot_conversations(id) on delete cascade,
  sender text not null check (sender in ('visitor','bot','system')),
  message text not null,
  treatment_context text,
  intent text,
  stage text,
  route text,
  city text,
  created_at timestamptz not null default now()
);

create index if not exists idx_bot_conversations_last_message on public.bot_conversations (last_message_at desc);
create index if not exists idx_bot_conversations_treatment on public.bot_conversations (treatment_context);
create index if not exists idx_bot_messages_conversation_created on public.bot_messages (conversation_id, created_at);

alter table public.bot_conversations enable row level security;
alter table public.bot_messages enable row level security;

grant insert on table public.bot_conversations to anon, authenticated;
grant insert on table public.bot_messages to anon, authenticated;
grant select, update, delete on table public.bot_conversations to authenticated;
grant select, update, delete on table public.bot_messages to authenticated;
grant usage, select on sequence public.bot_messages_id_seq to anon, authenticated;

drop policy if exists "Bot can create conversations" on public.bot_conversations;
create policy "Bot can create conversations" on public.bot_conversations for insert to anon, authenticated with check (true);

drop policy if exists "Admins can read conversations" on public.bot_conversations;
create policy "Admins can read conversations" on public.bot_conversations for select to authenticated
using (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.role = 'admin'));

drop policy if exists "Admins can update conversations" on public.bot_conversations;
create policy "Admins can update conversations" on public.bot_conversations for update to authenticated
using (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.role = 'admin'))
with check (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.role = 'admin'));

drop policy if exists "Admins can delete conversations" on public.bot_conversations;
create policy "Admins can delete conversations" on public.bot_conversations for delete to authenticated
using (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.role = 'admin'));

drop policy if exists "Bot can create messages" on public.bot_messages;
create policy "Bot can create messages" on public.bot_messages for insert to anon, authenticated
with check (exists (select 1 from public.bot_conversations c where c.id = conversation_id));

drop policy if exists "Admins can read messages" on public.bot_messages;
create policy "Admins can read messages" on public.bot_messages for select to authenticated
using (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.role = 'admin'));

drop policy if exists "Admins can update messages" on public.bot_messages;
create policy "Admins can update messages" on public.bot_messages for update to authenticated
using (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.role = 'admin'))
with check (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.role = 'admin'));

drop policy if exists "Admins can delete messages" on public.bot_messages;
create policy "Admins can delete messages" on public.bot_messages for delete to authenticated
using (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.role = 'admin'));
